### ISSUE TITLE
syncEntityEvents should throw error when entity is not defined

### ISSUE THREAD

**Issue by ianmstew** [Squareknot/marionette.state#12]
Currently `syncEntityEvents` will call handlers with an undefined entity.  Is this ideal, or is an error more appropriate?

Edit: Yes, there's no point to syncing entity events without an entity.  Moving forward with this.

**Comment by ianmstew** [comment]
Fixed in `1.0.0`

**Comment by sayra90** [comment]
Hey ya can you remove me from these emails? Gracias.

**Comment by ianmstew** [comment]
I believe you have to do that yourself!  Check your Github notification
preferences.

Ian
