### ISSUE TITLE
Will it work with Mn v3?

### ISSUE THREAD

**Issue by RohovDmytro** [Squareknot/marionette.state#24]

**Comment by loriensleafs** [comment]
I'd also love to know this.

**Comment by loriensleafs** [comment]
@rogovdm doesn't appear to be.  Not really clear on if the plugin is being actively maintained anymore.

**Comment by loriensleafs** [comment]
@rogovdm I replaced all instances of 'bindEntityEvents' with 'bindEvents' in Marionette.State.  So far that seems to have everything working correctly with Mn v3.
