### ISSUE TITLE
Allow state to be persisted

### ISSUE THREAD

**Issue by marfire** [Squareknot/marionette.state#5]
I really like the idea behind this project, and the documentation is great.

It seems to me, though, that the abstraction is not quite right. The description focuses on a distinction between persisted data and transient view state. However, it's a pretty common pattern to destroy and recreate views repeatedly over the lifecycle of an application. Imagine a single page application where the user is switching between views. It's a lot simpler (and more memory friendly) to just destroy the view when the user pages away. If the user comes back, though, you want to recreate the view, including any view-specific state.

So I think that _persistence_ is really an orthogonal concern to the separation of model data and view data. 

It's not clear to me whether there's a way to persist the view `State` and pass it to a newly created `View`. Is there is, great. My suggestion is to make that a first-class part of the API and documentation.

**Comment by ianmstew** [comment]
@marfire This is excellent feedback, and a huge encouragement.  Within the Squareknot architecture we have been grappling with this very concept.  What we want from state management is for it to exist on any strata, including at the long-lived application and sub-application levels.
1. At the application.  This state lives for the lifecycle of the application and could potentially be serialized to LocalStore or a server endpoint.  In Squareknot, this state begins with defaults on refresh, but further persistence could also be useful.  This is **global application state**.
2. At the sub-application (or module, or page--whatever you call a "routable unit that serves a consolidated purpose").  This state lives for the lifecycle of the sub-application and transcends view construction and destruction, but is _passed down_ into the views when the sub-application is accessed.  This is **sub-application state**, and is probably the most useful.
3. At the component (or view).  This state lives and dies with the views and serves to move view-specific state logic out of the view itself, however this may be initialized/synced with application or sub-application state.

Marionette.State API/documentation has been focused on the third, mainly until we solved higher level state with the same simplicity and clarity of message.  I think we're now ready to expand the library and documentation to cover cases 1 and 2, especially considering that we have just recently succeeded in using it in that way.

**Comment by marfire** [comment]
Thanks for your explanation, your tiered structured makes sense to me.

I've been doing something more or less like that, but in an ad hoc way (i.e. designed to work with my specific application rather than being generalizable). My units of state for the tiers have been Backbone models or Javascript objects, communicating via Backbone events or Backbone.Radio channels. The main thing is having the data flow in one direction, and having one source of truth for any bit of state, with other representations of that data updating themselves in response.

Like I said, though, it's all very ad hoc. So I'll look forward to following your progress and seeing what you come up with.

**Comment by ianmstew** [comment]
@marfire It sounds like we're heading in the same direction with tiered state, as well as @paulfalgout in his https://github.com/RoundingWellOS/marionette.toolkit.

I like what you said, "single source of truth for any bit of state"; I have heard "single search of truth" describing a global store before, making wonderful claims of being able to bookmark your entire application state, but that works against modularization in my view.  I am not saying there aren't use cases for one big global store, but I have found exactly what you said, tiered state treated like the single source of truth in its own "module", to be highly nestable/repeatable/maintainable.

I am halfway finished with unit tests and API update/doc re-write, so I hope to get that out in a couple more weeks and see if that furthers the conversation.

**Comment by ianmstew** [comment]
I just completed a massive overhaul to the docs that hopefully addresses a tiered approach to both transient and long-lived state.  Let me know if you have any thoughts, because it's a huge challenge to tackle all levels of complexity with a simple message.
